server:
  port: 7777

logging:
  level:
    root: DEBUG
    javax.management: ERROR
    org.springframework.security.web.FilterChainProxy: DEBUG

spring:
  application:
    name: j-sso
  security:
    oauth2:
      authorizationserver:
        issuer-url: http://localhost:7777
        introspection-endpoint: /oauth2/token-info
      client:
        registration:
          github:
            clientId: 9a86f169a6c97e5de840
            clientSecret: 872eafd2c649ed2e78d669e332edf7dc32566e91

#          yandex:
#            clientId: d0282255be2245fba3aa5c26e75e0ab1
#            clientSecret: 36492b46ab9b42cdbe335b5930935793
          yandex:
            provider: yandex
            clientId: d0282255be2245fba3aa5c26e75e0ab1
            clientSecret: 36492b46ab9b42cdbe335b5930935793
            redirect-uri: http://localhost:7777/login/oauth2/code/yandex
            authorizationGrantType: authorization_code
            clientName: Yandex

        provider:
          yandex:
            authorization-uri: https://oauth.yandex.ru/authorize
            token-uri: https://oauth.yandex.ru/token
            user-name-attribute: default_email
            userInfoUri: https://login.yandex.ru/info

yandex-avatar-url: https://avatars.yandex.net/get-yapic/34/islands-retina-50