server:
  port: 7777

logging:
  level:
    root: DEBUG
    javax.management: ERROR
    org.springframework.security.web.FilterChainProxy: DEBUG

spring:
  security:
    oauth2:
      authorizationserver:
        issuer-url: http://localhost:7777
        introspection-endpoint: /oauth2/token-info
      client:
        registration:
          github:
            clientId: 9a86f169a6c97e5de840
            clientSecret: bc5c226ad9188b160dfbb92cbf0eb3184b6ed374

