server:
  port: 7777

logging:
  level:
    root: DEBUG
    javax.management: ERROR
    org.springframework.security.web.FilterChainProxy: DEBUG

spring:
  application:
    name: j-sso
  liquibase:
    enabled: true
    change-log: classpath:database/db.changelog.yaml
    contexts: dev, prod
  datasource:
    url: "jdbc:postgresql://localhost:5435/j-sso"
    username: "user"
    password: "user"
    driver-class-name: "org.postgresql.Driver"
    hikari:
      connection-timeout: 30000
      connection-test-query: select 1
      maximum-pool-size: 10
      minimum-idle: 10
      initialization-fail-timeout: 1
      leak-detection-threshold: 0
      pool-name: "HikariPool-j-sso"
      register-mbeans: true
    jpa:
      show-sql: false
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      open-in-view: false
  security:
    oauth2:
      authorizationserver:
        issuer-url: http://localhost:7777
        introspection-endpoint: /oauth2/token-info
      client:
        registration:
          github:
            clientId: 9a86f169a6c97e5de840
            clientSecret: bc5c226ad9188b160dfbb92cbf0eb3184b6ed374

#          yandex:
#            clientId: d0282255be2245fba3aa5c26e75e0ab1
#            clientSecret: 36492b46ab9b42cdbe335b5930935793
          yandex:
            provider: yandex
            clientId: d0282255be2245fba3aa5c26e75e0ab1
            clientSecret: 36492b46ab9b42cdbe335b5930935793
            redirect-uri: http://localhost:7777/login/oauth2/code/yandex
            authorizationGrantType: authorization_code
            clientName: Yandex

        provider:
          yandex:
            authorization-uri: https://oauth.yandex.ru/authorize
            token-uri: https://oauth.yandex.ru/token
            user-name-attribute: default_email
            userInfoUri: https://login.yandex.ru/info

yandex-avatar-url: https://avatars.yandex.net/get-yapic/34/islands-retina-50

---
spring:
  config:
    activate:
      on-profile: production
  liquibase:
    contexts: prod

---
spring:
  config:
    activate:
      on-profile: development
  liquibase:
    contexts: prod, dev